### ISSUE TITLE
Sync tosca-parser with upstream

### ISSUE THREAD

**Issue by abitrolly** [ispras/clouni#34]
Two projects are out of sync, but it doesn't looks like there are too much changes between them.

https://github.com/openstack/tosca-parser/compare/master...bura2017:master

Why not send PR upstream?

**Comment by bura2017** [comment]
Pull requests were send to the upstream project tosca-parser, but it takes time for OpenStack developers to accept them

**Comment by abitrolly** [comment]
Looks like PRs are not here https://github.com/openstack/tosca-parser/pulls

Where are they located?

**Comment by bura2017** [comment]
All contributions to the OpenStack projects must be made through https://review.opendev.org/q/status:open+-is:wip
Pull requests to github are ignored

**Comment by bura2017** [comment]
Actually all my contribution commits were already added to the upstream, so I checked and tosca-parser can be used from upstream for now

**Comment by abitrolly** [comment]
Looks like this https://review.opendev.org/c/openstack/tosca-parser/+/735624

But for some reason the GitHub diff is still showing changes.

**Comment by bura2017** [comment]
Ok, I have updated our forked tosca-parser repo, it had some small changes in setup.cfg and some other non code files
